"""add logic file support

Revision ID: 04f80e2ba1e3
Revises: 6ece98a147f6
Create Date: 2026-06-18 11:58:16.031576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f80e2ba1e3'
down_revision: Union[str, Sequence[str], None] = '6ece98a147f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('logic_filename', sa.String(), nullable=True))
    op.add_column('ai_models', sa.Column('logic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'logic_path')
    op.drop_column('ai_models', 'logic_filename')
    # ### end Alembic commands ###
