"""make event model nullable

Revision ID: 6ece98a147f6
Revises: 11e4cc5f6a7c
Create Date: 2026-06-15 20:32:34.045495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ece98a147f6'
down_revision: Union[str, Sequence[str], None] = '11e4cc5f6a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('events_model_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'ai_models', ['model_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_model_id_fkey'), 'events', 'ai_models', ['model_id'], ['id'])
    op.alter_column('events', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
